var EVENT_NAVIGATION_NAVIGATED        = 'EVENT_NAVIGATION_NAVIGATED';
var EVENT_NAVIGATION_FOLDER_ACTIVATED = 'EVENT_NAVIGATION_FOLDER_ACTIVATED';
var EVENT_NAVIGATION_RECORDS_LOADED   = "EVENT_NAVIGATION_RECORDS_LOADED";
var EVENT_NAVIGATION_FOLDERS_LOADED   = "EVENT_NAVIGATION_FOLDERS_LOADED";
var EVENT_NAVIGATION_REFRESHED        = "EVENT_NAVIGATION_REFRESHED";

var EVENT_DETAIL_MODEL_LOADED   = "EVENT_DETAIL_MODEL_LOADED";
var EVENT_DETAIL_MODEL_CLEARED  = "EVENT_DETAIL_MODEL_CLEARED";
var EVENT_DETAIL_RECORD_LOADED  = "EVENT_DETAIL_RECORD_LOADED";
var EVENT_DETAIL_RECORD_SAVED   = "EVENT_DETAIL_RECORD_SAVED";
var EVENT_DETAIL_RECORD_CLEARED = "EVENT_DETAIL_RECORD_CLEARED";

// Commands
var COMMAND_LAYOUT                  = "COMMAND_LAYOUT";
var COMMAND_LAYOUT_LANDSCAPE        = "COMMAND_LAYOUT_LANDSCAPE";
var COMMAND_LAYOUT_PORTRAIT         = "COMMAND_LAYOUT_PORTRAIT";
var COMMAND_LAYOUT_EXPANDED         = "COMMAND_LAYOUT_EXPANDED";
var COMMAND_LAYOUT_CONTENTAREA      = "COMMAND_LAYOUT_CONTENTAREA";

var COMMAND_DESIGNMODE_GLOBAL       = "COMMAND_DESIGNMODE_GLOBAL";
var COMMAND_DESIGNMODE_NAVIGATION   = "COMMAND_DESIGNMODE_NAVIGATION";

var COMMAND_NAVIGATION_LOAD        ='COMMAND_NAVIGATION_LOAD';
var COMMAND_NAVIGATION_NAVIGATE    ='COMMAND_NAVIGATION_NAVIGATE';
var COMMAND_NAVIGATION_NAVIGATE_UP ='COMMAND_NAVIGATION_NAVIGATE_UP';
var COMMAND_NAVIGATION_DELETE      ='COMMAND_NAVIGATION_DELETE';
var COMMAND_NAVIGATION_REFRESH     ='COMMAND_NAVIGATION_REFRESH';
var COMMAND_NAVIGATION_LOCK        ='COMMAND_NAVIGATION_LOCK';

var COMMAND_DETAIL_MODEL_LOAD      = "COMMAND_DETAIL_MODEL_LOAD";
var COMMAND_DETAIL_RECORD_LOAD     = "COMMAND_DETAIL_RECORD_LOAD";
var COMMAND_DETAIL_RECORD_SAVE     = "COMMAND_DETAIL_RECORD_SAVE";
var COMMAND_DETAIL_RECORD_REFRESH  = "COMMAND_DETAIL_RECORD_REFRESH";
var COMMAND_DETAIL_RECORD_CLEAR    = "COMMAND_DETAIL_RECORD_CLEAR";
var COMMAND_DETAIL_RECORD_CREATE   = "COMMAND_DETAIL_RECORD_CREATE";
var COMMAND_DETAIL_RECORD_DELETE   = "COMMAND_DETAIL_RECORD_DELETE";


function coreTrigger(event, arg){
 //  console.log(event);
 //  if(arg)
 //  	console.log(arg);
   $(document).trigger(event,arg);
}