<?php


$PHPBLOCKS_DEMO = false;

$SESSION_DEMO_CONTENT_KEY ="DEMO_XML_CONTENT";

$PHPBLOCKS_CONFDIR   = dirname(__FILE__);
$PHPBLOCKS_ROOTDIR   = dirname($PHPBLOCKS_CONFDIR);
$PHPBLOCKS_DATADIR   = $PHPBLOCKS_ROOTDIR . "/data/";
$PHPBLOCKS_PLUGINDIR = $PHPBLOCKS_ROOTDIR . "/plugins/";

date_default_timezone_set("Europe/Dublin");
?>
